asset: https://github.com/juliuscanute/jbeacon/releases/download/$STABLE_VERSION/jbeacon.zip
tap: juliuscanute/homebrew-formulae/jbeacon.rb
template: >
  class Jbeacon < Formula
    desc     "$REPO_DESCRIPTION"
    homepage "$REPO_WEBITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"

    def install
      prefix.install "jbeacon"
    end
  end
