name: Swift

on:
  push:
    tags: 'v*.*.*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-build@2138f429e7bebe426d65985aca0dbad5370aa697
      #   cp "$IOS_DIR/MultiConfig-${CONFIGURATION}.zip" .
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: jbeacon/jbeacon.xcodeproj
        scheme: jbeacon
        configuration: Release
    - name: Package Zip
      run: |
          export BUILD_DIR=$(xcodebuild -project jbeacon/jbeacon.xcodeproj -scheme jbeacon -configuration Release -showBuildSettings  | grep -m 1 "BUILT_PRODUCTS_DIR" | grep -oEi "\/.*")
          (cd "$BUILD_DIR" ; zip -r jbeacon.zip ./jbeacon)
          cp "$BUILD_DIR/jbeacon.zip" .
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: jbeacon
        path: ./jbeacon.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            jbeacon.zip
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    - uses: mislav/bump-homebrew-formula-action@v1
      if: "!contains(github.ref, '-')" # skip prereleases
      with:
        formula-name: jbeacon
        homebrew-tap: juliuscanute/homebrew-formulae
        base-branch: master
        download-url: https://github.com/juliuscanute/jbeacon/releases/download/{{version}}/jbeacon.zip
        commit-message: commit jbeacon configuration
      env:
        COMMITTER_TOKEN: ${{ secrets.CI_TOKEN }}
