name: Swift

on:
  push:
    tags: 'v*.*.*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-build@2138f429e7bebe426d65985aca0dbad5370aa697
      #   cp "$IOS_DIR/MultiConfig-${CONFIGURATION}.zip" .
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        project: jbeacon/jbeacon.xcodeproj
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: jbeacon
        path: ./jbeacon/build/Release/jbeacon 
    - name: Package Zip
      run: (cd ./jbeacon/build/Release/ ; zip -r jbeacon.zip ./jbeacon)
    - name: Copy Zip
      run: cp ./jbeacon/build/Release/jbeacon.zip .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            jbeacon.zip
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
